import { EVCar } from './types';

export const mockEVCars: EVCar[] = [
  {
    id: '1',
    name: 'Tesla Model 3',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2024,
    price: 45000,
    image: ' ',
    category: 'Sedan',
    specs: {
      range: 510,
      battery: 82,
      charging: '30 minutes (DC fast)',
      topSpeed: 261,
      acceleration: '3.1s',
      seats: 5,
      power: 450,
    },
    features: [
      'Autopilot',
      'Full Self-Driving Capability',
      'Premium Audio System',
      '15-inch Touchscreen',
      'Glass Roof',
      'Heated Seats',
      'Over-the-Air Updates',
      'Navigate on Autopilot',
    ],
    description: 'The Tesla Model 3 is a premium electric sedan that combines exceptional performance with cutting-edge technology. With its sleek design and industry-leading range, it offers an unmatched driving experience.',
  },
  {
    id: '2',
    name: 'BYD Atto 3',
    brand: 'BYD',
    model: 'Atto 3',
    year: 2024,
    price: 35000,
    image: '',
    category: 'SUV',
    specs: {
      range: 420,
      battery: 60.5,
      charging: '45 minutes (DC fast)',
      topSpeed: 160,
      acceleration: '7.3s',
      seats: 5,
      power: 201,
    },
    features: [
      'Panoramic Sunroof',
      '12.8-inch Rotating Touchscreen',
      'Adaptive Cruise Control',
      'Lane Keep Assist',
      '360° Camera',
      'Ventilated Seats',
      'DiLink Smart System',
      'Voice Control',
    ],
    description: 'The BYD Atto 3 is a versatile electric SUV that offers exceptional value and innovative technology. With its spacious interior and impressive range, it\'s perfect for families and urban commuters alike.',
  },
  {
    id: '3',
    name: 'Nissan Leaf',
    brand: 'Nissan',
    model: 'Leaf',
    year: 2024,
    price: 28000,
    image: '',
    category: 'Hatchback',
    specs: {
      range: 385,
      battery: 62,
      charging: '40 minutes (DC fast)',
      topSpeed: 157,
      acceleration: '7.9s',
      seats: 5,
      power: 214,
    },
    features: [
      'ProPILOT Assist',
      'e-Pedal',
      'Apple CarPlay',
      'Android Auto',
      'Intelligent Around View Monitor',
      'Bose Premium Audio',
      'NissanConnect EV',
      'Heated Steering Wheel',
    ],
    description: 'The Nissan Leaf is the world\'s best-selling electric car, offering practicality, comfort, and reliability. Its advanced e-Pedal technology and ProPILOT Assist make driving effortless and enjoyable.',
  },
  {
    id: '4',
    name: 'Hyundai Ioniq 5',
    brand: 'Hyundai',
    model: 'Ioniq 5',
    year: 2024,
    price: 43000,
    image: '',
    category: 'Crossover',
    specs: {
      range: 481,
      battery: 77.4,
      charging: '18 minutes (DC fast)',
      topSpeed: 185,
      acceleration: '5.2s',
      seats: 5,
      power: 320,
    },
    features: [
      'Ultra-Fast 800V Charging',
      'Vehicle-to-Load (V2L)',
      'Augmented Reality HUD',
      'Relaxation Comfort Seats',
      'Ambient Lighting',
      'Smart Cruise Control',
      'Remote Smart Parking Assist',
      'Digital Side Mirrors',
    ],
    description: 'The Hyundai Ioniq 5 revolutionizes electric mobility with its retro-futuristic design and ultra-fast charging capability. Experience the future of driving with its innovative features and spacious, lounge-like interior.',
  },
  {
    id: '5',
    name: 'VW ID.4',
    brand: 'Volkswagen',
    model: 'ID.4',
    year: 2024,
    price: 41000,
    image: '',
    category: 'SUV',
    specs: {
      range: 443,
      battery: 82,
      charging: '35 minutes (DC fast)',
      topSpeed: 180,
      acceleration: '6.2s',
      seats: 5,
      power: 295,
    },
    features: [
      'ID.Light',
      'Augmented Reality Head-Up Display',
      'IQ.DRIVE Assistance Systems',
      '12-inch Touchscreen',
      'Wireless Charging',
      'Harman Kardon Audio',
      'Travel Assist',
      '3D Digital Cockpit',
    ],
    description: 'The Volkswagen ID.4 combines German engineering excellence with electric innovation. This spacious SUV offers a premium driving experience, advanced technology, and impressive range for all your journeys.',
  },
  {
    id: '6',
    name: 'Kia EV6',
    brand: 'Kia',
    model: 'EV6',
    year: 2024,
    price: 48000,
    image: '',
    category: 'Crossover',
    specs: {
      range: 528,
      battery: 77.4,
      charging: '18 minutes (DC fast)',
      topSpeed: 185,
      acceleration: '5.1s',
      seats: 5,
      power: 320,
    },
    features: [
      '800V Ultra-Fast Charging',
      'Vehicle-to-Load',
      'Augmented Reality HUD',
      'Highway Driving Assist 2',
      'Remote Smart Parking',
      'Meridian Premium Audio',
      'Dual Curved Display',
      'Relaxation Seats',
    ],
    description: 'The Kia EV6 is a stunning crossover that delivers exhilarating performance and cutting-edge technology. With its award-winning design and ultra-fast charging, it sets new standards in electric mobility.',
  },
  {
    id: '7',
    name: 'Polestar 2',
    brand: 'Polestar',
    model: '2',
    year: 2024,
    price: 50000,
    image: '',
    category: 'Sedan',
    specs: {
      range: 470,
      battery: 78,
      charging: '40 minutes (DC fast)',
      topSpeed: 205,
      acceleration: '4.7s',
      seats: 5,
      power: 408,
    },
    features: [
      'Android Automotive OS',
      'Google Assistant Built-in',
      'Pilot Assist',
      'Harman Kardon Audio',
      'WeaveTech Vegan Interior',
      'Pixel LED Headlights',
      'Phone Key',
      'Wireless Charging',
    ],
    description: 'The Polestar 2 is a premium electric performance sedan that combines Scandinavian design with cutting-edge technology. Experience the perfect balance of sustainability, luxury, and performance.',
  },
  {
    id: '8',
    name: 'MG ZS EV',
    brand: 'MG',
    model: 'ZS EV',
    year: 2024,
    price: 32000,
    image: '',
    category: 'SUV',
    specs: {
      range: 440,
      battery: 72.6,
      charging: '45 minutes (DC fast)',
      topSpeed: 175,
      acceleration: '8.2s',
      seats: 5,
      power: 177,
    },
    features: [
      '10.1-inch Touchscreen',
      'Apple CarPlay',
      'Android Auto',
      'Panoramic Sunroof',
      '360° Camera',
      'Adaptive Cruise Control',
      'Lane Keep Assist',
      'MG iSMART System',
    ],
    description: 'The MG ZS EV offers exceptional value as an affordable electric SUV with impressive range and features. Perfect for families seeking a practical and economical electric vehicle solution.',
  },
  {
    id: '9',
    name: 'BMW iX',
    brand: 'BMW',
    model: 'iX',
    year: 2024,
    price: 85000,
    image: '',
    category: 'SUV',
    specs: {
      range: 630,
      battery: 111.5,
      charging: '35 minutes (DC fast)',
      topSpeed: 200,
      acceleration: '4.6s',
      seats: 5,
      power: 516,
    },
    features: [
      'iDrive 8',
      'Curved Display',
      'Laser Headlights',
      'Bowers & Wilkins Audio',
      'Sky Lounge Panoramic Roof',
      'Parking Assistant Plus',
      'Driving Assistant Professional',
      'Comfort Access',
    ],
    description: 'The BMW iX represents the pinnacle of luxury electric SUVs, combining stunning design with exceptional performance and range. Experience ultimate comfort and cutting-edge technology in this flagship model.',
  },
  {
    id: '10',
    name: 'Chevy Bolt EUV',
    brand: 'Chevrolet',
    model: 'Bolt EUV',
    year: 2024,
    price: 29000,
    image: '',
    category: 'Crossover',
    specs: {
      range: 402,
      battery: 65,
      charging: '45 minutes (DC fast)',
      topSpeed: 150,
      acceleration: '7.0s',
      seats: 5,
      power: 200,
    },
    features: [
      'Super Cruise',
      '10.2-inch Touchscreen',
      'HD Surround Vision',
      'Wireless Charging',
      'Apple CarPlay',
      'Android Auto',
      'Teen Driver',
      'OnStar Services',
    ],
    description: 'The Chevrolet Bolt EUV is a practical and affordable electric crossover with impressive technology. Featuring GM\'s Super Cruise hands-free driving system, it offers great value and peace of mind.',
  },
];
